# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [2]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    # 减去最大值以提高数值稳定性
    x_max = tf.reduce_max(x, axis=-1, keepdims=True)
    x_stable = x - x_max
    # 计算指数
    exp_x = tf.exp(x_stable)
    # 求和
    sum_exp_x = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    # 计算概率
    prob_x = exp_x / sum_exp_x
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    prob_x = 1 / (1 + tf.exp(-x))
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [4]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    # 避免 log(0) 导致数值不稳定，添加一个很小的 epsilon
    epsilon = 1e-10
    x_clipped = tf.clip_by_value(x, epsilon, 1.0 - epsilon)
    # 计算交叉熵: -sum(label * log(x))
    # 对于 one-hot label，只有正确类别的项非零
    loss_per_sample = -tf.reduce_sum(label * tf.math.log(x_clipped), axis=-1)
    # 返回平均损失
    loss = tf.reduce_mean(loss_per_sample)
    ##########
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [5]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    # 输入 x 是 sigmoid 后的概率（已经过sigmoid激活）
    # label 是二分类标签（0或1）
    
    # 避免 log(0) 导致数值不稳定，添加一个很小的 epsilon
    epsilon = 1e-10
    x_clipped = tf.clip_by_value(x, epsilon, 1.0 - epsilon)
    # 二分类交叉熵公式: -[y * log(p) + (1-y) * log(1-p)]
    # y: 真实标签，p: 预测概率
    loss_per_sample = - (label * tf.math.log(x_clipped) + 
                        (1 - label) * tf.math.log(1 - x_clipped))
    # 返回平均损失
    loss = tf.reduce_mean(loss_per_sample)
    ##########
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 0. 1. 1. 0. 0. 1. 1. 0. 1.]


True